version: "3.8"
services:
  postgres:
    image: "postgres:13.3"
    container_name: pg_db
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "passwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./init_scripts:/docker-entrypoint-initdb.d:ro"
      - "./pgdata:/var/lib/postgresql/data:rw"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -p passwd" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

